### ISSUE TITLE
导入都有问题。依赖不识别。

### ISSUE THREAD

**Issue by Dreamskya** [Will-Ls/WeiYue#1]
依赖这里全是有问题dependencies
lib都没有的。
不知道大神是怎么编译的呢

**Comment by Will-Ls** [comment]
你好，你这边是clone导入有问题是吗？如果是的话，重新导入下应该就 ok 的 
File->Import Project->选择下载的文件夹
如果还不行的话，麻烦截下图 谢谢

**Comment by Dreamskya** [comment]
你的项目用到kotlin。可以不用吗？删掉是否可以呢？



zhangtao@simtoo.com
 
发件人： Will
发送时间： 2017-11-07 23:32
收件人： Will-Ls/WeiYue
抄送： Dreamskya; Author
主题： Re: [Will-Ls/WeiYue] 导入都有问题。依赖不识别。 (#1)
你好，你这边是clone导入有问题是吗？如果是的话，重新导入下应该就 ok 的
File->Import Project->选择下载的文件夹
如果还不行的话，麻烦截下图 谢谢

**Comment by Will-Ls** [comment]
你好我这边看不到你的截图，你加我QQ 吧 283706284
