### ISSUE TITLE
首次安装欢迎界面图片不显示

### ISSUE THREAD

**Issue by albertizzy** [Will-Ls/WeiYue#13]
如题，发生在7.0的系统上

**Comment by Will-Ls** [comment]
您好，首页欢迎页使用的图片是高清图片1920 * 1080分辨率，所以加载时比较慢，而且使用的是别人提供的 Api 可能不是很稳定。
另外，图片来源于必应 [传送门](https://www.dujin.org/fenxiang/jiaocheng/3618.html)，该作者提供了 1366 * 768 和 1920 * 1080 两种分辨率，使用前者加载速度会快一点。
1366 * 768分辨率图片地址：`http://api.dujin.org/bing/1366.php`
1920 * 1080分辨率图片地址： `http://api.dujin.org/bing/1920.php`
