### ISSUE TITLE
你是不是在com.will.weiyue.component包下少写了一个东西

### ISSUE THREAD

**Issue by yixiaoqingcheng** [Will-Ls/WeiYue#2]
我下载的是java版的，少写个DaggerApplicationComponent！下下来不能用很捉急

**Comment by Will-Ls** [comment]
您好，这个文件是需要 编译生成的 点击这里。
![image](https://user-images.githubusercontent.com/27726553/34859272-22657e60-f790-11e7-8554-741a4b9fb457.png)
