### ISSUE TITLE
是不是文件没有上传完整？

### ISSUE THREAD

**Issue by uty3714** [Will-Ls/WeiYue#3]
本地跑不了 缺东西

**Comment by Will-Ls** [comment]
您好，clone 之后 点一下这里

![image](https://user-images.githubusercontent.com/27726553/34932397-a5f201ca-fa0d-11e7-8597-29ed20f8a2db.png)

**Comment by uty3714** [comment]
好 谢谢

**Comment by freeman1229** [comment]
下载后import工程后，报错！！！每个Fragment都缺少DaggerHttpComponent类

**Comment by Will-Ls** [comment]
@freeman1229 您好，这个文件是编译生成的，参照 #2
