### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by JIAN006** [Will-Ls/WeiYue#5]
![1516010600 1](https://user-images.githubusercontent.com/26914725/34937125-9de85194-fa1e-11e7-9abf-8b1fa41b7f49.jpg)

我想问一下这个type是从哪里传进去的,找了半天没找着...

**Comment by Will-Ls** [comment]
在 [DetailPresenter](https://github.com/Will-Ls/WeiYue/blob/master/app/src/main/java/com/will/weiyue/ui/news/presenter/DetailPresenter.java)中设置的
需在 [NewsDetail](https://github.com/Will-Ls/WeiYue/blob/master/app/src/main/java/com/will/weiyue/bean/NewsDetail.java) 中继承 MultiItemEntity 接口

```
public static class ItemBean implements Serializable, MultiItemEntity {
       // 省略代码..
        @Override
        public int getItemType() {
            return itemType;
        }

        public int itemType;
}
```

**Comment by JIAN006** [comment]
好的,非常感谢
