### ISSUE TITLE
com.will.weiyue.component.DaggerApplicationComponent这个类找不到

### ISSUE THREAD

**Issue by pjcchinaren** [Will-Ls/WeiYue#7]
MyApp类中  mApplicationComponent = DaggerApplicationComponent.builder()
                .applicationModule(new ApplicationModule(this))
                .httpModule(new HttpModule())
                .build();
DaggerApplicationComponent这个类找不到

**Comment by pjcchinaren** [comment]
com.will.weiyue.component这个包里是不是有些类没有提交到Github上？

**Comment by Will-Ls** [comment]
您好，这个文件是编译生成的，参照 #2

**Comment by pjcchinaren** [comment]
多谢，已经找到了
