### ISSUE TITLE
问题求助

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [Will-Ls/WeiYue#9]
你好作者正在学习你的代码 但有个地方实在看不懂 请问
![jfak bt i2tf 7y4qe6dr](https://user-images.githubusercontent.com/25426589/35433889-018df4ca-02c0-11e8-8c28-a7a458b2a93d.png)这里是什么意思呢

**Comment by Will-Ls** [comment]
您好，这是煎蛋接口默认的参数
![15169657265283](https://user-images.githubusercontent.com/27726553/35437633-468291f4-02ce-11e8-9597-3edf94883af2.jpg)
